### ISSUE TITLE
'npm install' throws error on installing magicmirror dependencies as well as for MMM-susi -ai

### ISSUE THREAD

**Issue by nileshgulia1** [fossasia/MMM-SUSI-AI#39]
nilesh@nilesh:~/MagicMirror$ npm install

> uws@0.14.5 install /home/nilesh/MagicMirror/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> electron-chromedriver@1.7.1 install /home/nilesh/MagicMirror/node_modules/electron-chromedriver
> node ./download-chromedriver.js

> electron@1.7.8 postinstall /home/nilesh/MagicMirror/node_modules/electron
> node install.js

/home/nilesh/MagicMirror/node_modules/electron/install.js:48
  throw err
  ^

Error: Failed to find Electron v1.7.8 for linux-x64 at https://github.com/electron/electron/releases/download/v1.7.8/electron-v1.7.8-linux-x64.zip
    at Request.<anonymous> (/home/nilesh/MagicMirror/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/home/nilesh/MagicMirror/node_modules/request/request.js:1068:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
npm WARN grunt-stylelint@0.9.0 requires a peer of stylelint@^8.0.0 but none was installed.
npm WARN stylelint-config-standard@17.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
npm WARN stylelint-config-recommended@1.0.0 requires a peer of stylelint@^8.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nilesh/.npm/_logs/2017-09-24T19_11_16_513Z-debug.log

**Comment by nileshgulia1** [comment]
Error fixed after installing electron@1.7.6
